from . import help
from . import shaxsiy_tarkibga_oid
from . import tatillarga_oid
from . import umumiy_masalalargaoid
from . import admin
from . import start
from . import shartnoma
from . import buyruq
from . import orqaga
from . import orqaga1
from . import orqaga2
from . import Mehnat_munosabatlari
from . import FuqorolikShartnomasi
from . import kelishuvBitimlari
from . import hujjatQoshish
from . import hujjatqoshish1
from . import buyruqQoshishmenu
from . import shartnomandBuyruqQoshish
from . import buyruqQoshish
from . import tahrirlash
from . import tahrirlashMenu
from . import shartnomaTahrirlash
from . import buyruqTahrirlash
from . import echo
from . import orqaga3
