from . import boshMenu
from . import shartnoma
from . import buyruq
from . import adminmenu
from . import hujjatlarQoshish
from . import adminmenu1
from . import adminBuyruq
from . import tahrirlash
from . import shartnomaTahrirlash
from . import buyruqTahrirlash